### ISSUE TITLE
Enhanced config file support for ilber clones.

### ISSUE THREAD

**Issue by kozdincer** [igungor/ilberbot#1]
I want to clone ilber and use with another telegram bot. Because of api limits (images etc.)
For easy setup, configurations of all commands should be in one place.

**Comment by igungor** [comment]
Yup!

**Comment by igungor** [comment]
All configurations are in one place! :)

Just copy ilber.conf.example to ilber.conf and populate the configuration file with your credentials and stuff. I've put a description on commit log, in case goes unnoticed:

ilber.conf is basically a json file.
- "host", "port" and "debug" are obvious enough.
- "profile" enables an HTTP server on port 6060 to remote profile the
  bot, via `go tool pprof`. Handy stuff.
- "token" parameter can be provided from BotFather Telegram bot.
- "webhook" parameter is needed to notice Telegram servers that ilber is
  running on "webhook" url.
- "googleAPIKey" can be provided from google developer console. It is a
  generic API key for all the google services.
- "googleSearchEngineID" is a mandatory yet cumbersome thing which is
  needed to make the new google search API happy.
- "openWeatherMapAppID" is needed for forecasts and can be grabbed from
  `http://openweathermap.org/appid#get`

Cheers
